# Generated by Django 4.1.5 on 2023-01-15 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='date_changed',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='theme',
            field=models.TextField(),
        ),
    ]
