# Generated by Django 3.2.12 on 2023-01-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_person_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
