# Generated by Django 4.1.5 on 2023-01-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_blogpost_delete_choice_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
