# Generated by Django 4.1.5 on 2023-01-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obec', models.CharField(max_length=255, verbose_name='Obec')),
                ('kod_obce', models.CharField(max_length=255, verbose_name='Kod obce')),
                ('okres', models.CharField(max_length=255, verbose_name='Okres ')),
                ('kod_okresu', models.CharField(max_length=255, verbose_name='Kod okresu')),
                ('kraj', models.CharField(max_length=255, verbose_name='Kraj')),
                ('kod_kraje', models.CharField(max_length=255, verbose_name='Kod kraje')),
                ('psc', models.CharField(max_length=255, verbose_name='PSC')),
                ('latitude', models.FloatField(max_length=255, verbose_name='Latitude')),
                ('longitude', models.FloatField(max_length=255, verbose_name='Longitude')),
                ('url', models.URLField(max_length=255, verbose_name='Stranky obce')),
            ],
        ),
        migrations.CreateModel(
            name='Zastupitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Obec')),
                ('last_name', models.CharField(max_length=255, verbose_name='Kod obce')),
                ('titel', models.CharField(max_length=255, verbose_name='Okres ')),
                ('zastupitel', models.BooleanField(default=True, verbose_name='Zastupitel')),
                ('obec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.obec')),
            ],
        ),
        migrations.DeleteModel(
            name='ObceCr',
        ),
    ]
