# Generated by Django 4.1.5 on 2023-01-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_obec_kraj_id_alter_obec_kod_kraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='zastupitel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='zastupitel',
            name='telefon',
            field=models.CharField(blank=True, max_length=255, verbose_name='telefon'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='telefon',
            field=models.CharField(blank=True, max_length=255, verbose_name='telefon'),
        ),
        migrations.AlterField(
            model_name='obec',
            name='okres',
            field=models.CharField(max_length=255, verbose_name='Okres'),
        ),
        migrations.AlterField(
            model_name='zastupitel',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Jmeno'),
        ),
        migrations.AlterField(
            model_name='zastupitel',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Prijmeni'),
        ),
        migrations.AlterField(
            model_name='zastupitel',
            name='titel',
            field=models.CharField(max_length=255, verbose_name='Titul '),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Jmeno'),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Prijmeni'),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='titel',
            field=models.CharField(max_length=255, verbose_name='Titul '),
        ),
    ]
