# Generated by Django 4.1.5 on 2023-01-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_zastupitel_email_zastupitel_telefon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zastupitel',
            name='funkce',
            field=models.CharField(blank=True, max_length=255, verbose_name='funkce'),
        ),
        migrations.AddField(
            model_name='zastupitel',
            name='poznamky',
            field=models.TextField(blank=True, verbose_name='poznamky'),
        ),
        migrations.AddField(
            model_name='zastupitel',
            name='strana',
            field=models.CharField(blank=True, max_length=255, verbose_name='strana'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='funkce',
            field=models.CharField(blank=True, max_length=255, verbose_name='funkce'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='poznamky',
            field=models.TextField(blank=True, verbose_name='poznamky'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='strana',
            field=models.CharField(blank=True, max_length=255, verbose_name='strana'),
        ),
    ]
