# Generated by Django 4.1.5 on 2023-01-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_zastupitel_title_alter_zastupitelkraje_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='zastupitel',
            name='absolutni_hlasy',
            field=models.IntegerField(blank=True, default=None, verbose_name='Absolutní hlasy'),
        ),
        migrations.AddField(
            model_name='zastupitel',
            name='hlasy_v_procentech',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hlasy v procentech'),
        ),
        migrations.AddField(
            model_name='zastupitel',
            name='navrhujici_strana',
            field=models.CharField(blank=True, max_length=255, verbose_name='Navrhující strana'),
        ),
        migrations.AddField(
            model_name='zastupitel',
            name='vek',
            field=models.IntegerField(blank=True, default=None, verbose_name='věk'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='absolutni_hlasy',
            field=models.IntegerField(blank=True, default=None, verbose_name='Absolutní hlasy'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='hlasy_v_procentech',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hlasy v procentech'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='navrhujici_strana',
            field=models.CharField(blank=True, max_length=255, verbose_name='Navrhující strana'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='vek',
            field=models.IntegerField(blank=True, default=None, verbose_name='věk'),
        ),
    ]
