# Generated by Django 4.1.5 on 2023-01-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_zastupitelkraje_absolutni_hlasy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='absolutni_hlasy',
            field=models.IntegerField(blank=True, default=0, verbose_name='Absolutní hlasy'),
        ),
    ]
