# Generated by Django 4.1.5 on 2023-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_zastupitelkraje_absolutni_hlasy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zastupitel',
            name='absolutni_hlasy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Absolutní hlasy'),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='absolutni_hlasy',
            field=models.CharField(blank=True, max_length=255, verbose_name='Absolutní hlasy'),
        ),
    ]
