# Generated by Django 4.1.5 on 2023-01-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_alter_zastupitel_vek_alter_zastupitelkraje_vek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zastupitel',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='zastupitelkraje',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='zastupitel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='zastupitelkraje',
            name='last_name',
        ),
    ]
