# Generated by Django 4.1.5 on 2023-01-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_rename_first_name_zastupitel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zastupitel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='zastupitelkraje',
            name='name',
        ),
        migrations.AddField(
            model_name='zastupitel',
            name='first_name',
            field=models.CharField(default='a', max_length=255, verbose_name='Jmeno'),
        ),
        migrations.AddField(
            model_name='zastupitel',
            name='kod_obce',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kod obce'),
        ),
        migrations.AddField(
            model_name='zastupitel',
            name='last_name',
            field=models.CharField(default='a', max_length=255, verbose_name='Prijmeni'),
        ),
        migrations.AddField(
            model_name='zastupitel',
            name='title_b',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titul za'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='first_name',
            field=models.CharField(default='a', max_length=255, verbose_name='Jmeno'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='kod_kraje',
            field=models.CharField(blank=True, max_length=255, verbose_name='kod kraje'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='last_name',
            field=models.CharField(default='a', max_length=255, verbose_name='Prijmeni'),
        ),
        migrations.AddField(
            model_name='zastupitelkraje',
            name='title_b',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titul za'),
        ),
    ]
