# Generated by Django 4.1.5 on 2023-01-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_remove_zastupitel_name_remove_zastupitelkraje_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zastupitel',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Jmeno'),
        ),
        migrations.AlterField(
            model_name='zastupitel',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Prijmeni'),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Jmeno'),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Prijmeni'),
        ),
    ]
