# Generated by Django 4.1.5 on 2023-01-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_alter_zastupitel_birth_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zastupitel',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='zastupitel',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='zastupitelkraje',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='zastupitelkraje',
            name='birth_year',
        ),
        migrations.AlterField(
            model_name='zastupitel',
            name='birth_day',
            field=models.CharField(blank=True, max_length=255, verbose_name='den narození'),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='birth_day',
            field=models.CharField(blank=True, max_length=255, verbose_name='den narození'),
        ),
    ]
