# Generated by Django 4.1.5 on 2023-01-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_obec_zastupitel_delete_obcecr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kraj', models.CharField(max_length=255, verbose_name='Kraj')),
                ('kod_kraje', models.CharField(max_length=255, verbose_name='kod kraje')),
                ('latitude', models.FloatField(max_length=255, verbose_name='Latitude')),
                ('longitude', models.FloatField(max_length=255, verbose_name='Longitude')),
                ('url', models.URLField(max_length=255, verbose_name='Stranky kraje')),
            ],
        ),
        migrations.AlterField(
            model_name='obec',
            name='kod_kraje',
            field=models.CharField(max_length=255, verbose_name='kod kraje'),
        ),
        migrations.AlterField(
            model_name='obec',
            name='kraj',
            field=models.CharField(max_length=255, verbose_name='kraj'),
        ),
        migrations.CreateModel(
            name='ZastupitelKraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Obec')),
                ('last_name', models.CharField(max_length=255, verbose_name='Kod obce')),
                ('titel', models.CharField(max_length=255, verbose_name='Okres ')),
                ('zastupitel', models.BooleanField(default=True, verbose_name='Zastupitel')),
                ('kraj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.kraj')),
            ],
        ),
        migrations.AddField(
            model_name='obec',
            name='kraj_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.kraj'),
        ),
    ]
