# Generated by Django 4.1.5 on 2023-01-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_kraj_alter_obec_kod_kraje_alter_obec_kraj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obec',
            name='kraj_id',
        ),
        migrations.AlterField(
            model_name='obec',
            name='kod_kraje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.kraj'),
        ),
    ]
