# Generated by Django 4.1.5 on 2023-01-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_zastupitel_absolutni_hlasy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='absolutni_hlasy',
            field=models.IntegerField(blank=True, verbose_name='Absolutní hlasy'),
        ),
    ]
