# Generated by Django 4.1.5 on 2023-01-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_alter_zastupitel_absolutni_hlasy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zastupitel',
            name='vek',
            field=models.IntegerField(blank=True, verbose_name='věk'),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='vek',
            field=models.IntegerField(blank=True, verbose_name='věk'),
        ),
    ]
