# Generated by Django 4.1.5 on 2023-01-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_alter_zastupitel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zastupitel',
            name='birth_day',
            field=models.IntegerField(blank=True, verbose_name='den narození'),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='birth_day',
            field=models.IntegerField(blank=True, verbose_name='den narození'),
        ),
    ]
