# Generated by Django 4.1.5 on 2023-01-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_alter_zastupitel_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zastupitel',
            name='birth_month',
            field=models.IntegerField(blank=True, verbose_name='mesic narození'),
        ),
        migrations.AlterField(
            model_name='zastupitel',
            name='birth_year',
            field=models.IntegerField(blank=True, verbose_name='rok narození'),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='birth_month',
            field=models.IntegerField(blank=True, verbose_name='mesic narození'),
        ),
        migrations.AlterField(
            model_name='zastupitelkraje',
            name='birth_year',
            field=models.IntegerField(blank=True, verbose_name='rok narození'),
        ),
    ]
