# Generated by Django 4.1.5 on 2023-01-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_zastupitel_kraj'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolebVyslPrez2023Obec2kolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_obce', models.CharField(max_length=255, verbose_name='Číslo obce')),
                ('nazev_obce', models.CharField(max_length=255, verbose_name='Jméno obce')),
                ('hlasy_Pavel', models.CharField(max_length=255, verbose_name='Hlasy Petr Pavel')),
                ('hlasy_Babis', models.CharField(max_length=255, verbose_name='Hlasy Andrej Babis')),
                ('ucast_procenta', models.CharField(max_length=255, verbose_name='Účast v procentech')),
                ('platne_hlasy', models.CharField(max_length=255, verbose_name='Platné hlasy')),
                ('plat_hlas_procenta', models.CharField(max_length=255, verbose_name='Platné hlasy v procentech')),
                ('ucast_proc', models.CharField(max_length=255, verbose_name='Účast v procentech')),
                ('zapsani_volici', models.CharField(max_length=255, verbose_name='Zapsaní voliči')),
            ],
        ),
    ]
