# Generated by Django 4.1.5 on 2023-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_volebvyslprez2023obec1kolo_cislo_kraje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volebvyslprez2023obec1kolo',
            name='cislo_kraje',
            field=models.CharField(max_length=255, verbose_name='Číslo kraje'),
        ),
        migrations.AlterField(
            model_name='volebvyslprez2023obec2kolo',
            name='cislo_kraje',
            field=models.CharField(max_length=255, verbose_name='Číslo kraje'),
        ),
    ]
