# Generated by Django 4.1.5 on 2023-01-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_alter_volebvyslprez2023obec1kolo_cislo_kraje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volebvyslprez2023obec1kolo',
            name='ucast_procenta',
        ),
    ]
