# Generated by Django 4.1.5 on 2023-01-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_remove_volebvyslprez2023obec1kolo_ucast_procenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volebvyslprez2023obec2kolo',
            name='ucast_procenta',
        ),
    ]
