# Generated by Django 4.1.5 on 2023-01-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_person_phone_person_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
    ]
