# Generated by Django 4.1.5 on 2023-01-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_remove_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
