# Generated by Django 4.1.5 on 2023-01-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_remove_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
