# Generated by Django 4.1.5 on 2023-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název')),
                ('owner', models.IntegerField(default=1, verbose_name='Majitel')),
                ('title', models.CharField(max_length=255, verbose_name='Titulek')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('date_published', models.DateTimeField(verbose_name='Datum Zveřejnění')),
                ('date_changed', models.DateTimeField(verbose_name='Datum upravy')),
                ('likes', models.IntegerField(default=0, verbose_name='Líbí se')),
                ('read', models.IntegerField(default=0, verbose_name='Přečteno')),
                ('content', models.TextField()),
                ('theme', models.TextField(default='článek')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
